### ISSUE TITLE
RFC: Organize CSS packages

### ISSUE THREAD

**Issue by oscarotero** [CSS-Galore/registry#1]
In this issue, we want to discuss the best way to store and organize CSS packages for better reusability.

## How to organize the code

Currently, the registry works in the following way.

- The code is grouped in **packages**.  They contain CSS code for a specific purpose and are similar to NPM packages. Examples of packages could be [normalize.css](https://www.npmjs.com/package/normalize.css) or [animate.css](https://www.npmjs.com/package/animate.css).
- Every package has a README.md file with the description of the package, how to use it, the author, etc.
  - Is this file enough? Do we need a more structured format (like JSON, toml, etc) to store info like author, license, etc?
- Packages have one or more **modules**. Modules are individual pieces of code that you may use or not. For example, [animate.css](https://animate.style/) is a collection of CSS animations, every type of animation could be a module (bounce, flash, pulse, etc.
- This allows us to refer to a module with the `<package>/<module>` syntax. I.e. `animate.css/bounce`.

> [!note]
>
> Some package registries have the concept of "scope" to group different packages under the same scope (scopes used to be the author name or a framework with several packages) making the paths a bit bigger `<scope>/<package>/<module>`. Do we need it?
> 
> The problem I see is not all packages need a scope. It's pretty common to see scopes and packages with the same name. An alternative solution could be to allow submodules if needed. For example: `<package>/<module>/<submodule>`. This would fit well for simple packages (with just one module) and big packages with many modules and submodules.

## How to store modules?

The current modules are stored in HTML files. HTML is a very versatile format that can contain stuff of different types. The HTML follows the following structure:

```html
<!--
Comment with the module description in markdown format.
-->

<p>HTML elements for the demo</p>

<style>
  .host {
    /* User settings */
    ...
    /* Implementation */
    ...
  }
</style>

<style>
  /* Additional styles only for the demo */
</style>
```

- We use an HTML comment to include a description of the module in markdown format.
  - Is this enough? Should we have a more structured format like JSON or YAML?
- The first `<style>` element is considered the code of the module. It's the code that you will get when importing the module into your project.
- Additional `<style>` elements are considered styles for the demo but don't belong to the module. They are ignored when importing the module into a project.

This format allows us to store not only the CSS code of the module but also everything needed to test the code in a browser in just a single file. It works out of the box, without any tooling, just open this file in a browser and you will see a demo of the module.

## How to create the CSS code

The CSS code should be the most flexible and customizable as possible, CSS properties to configure the behavior are recommended. For example:

```css
/* Wrong: the code is not easily configurable */
button {
  color: white;
  background: blue;
}


/* Rigth: the configuration options are clearer */
button {
  --color: white;
  --bg-color: blue;

  color: var(--color);
  background: var(--bg-color);
}
```

- What happens if in our code we are using the same CSS properties for another purpose? Should we encourage the use of underscored property names?

```css
button {
  --_color: white;
  --_bg-color: blue;

  color: var(--_color);
  background: var(--_bg-color);
}
```

## How to fix class name conflict?

A CSS module can use a class name in the selector that is already being used in your project, which causes a conflict. This is why the code of the module must use the CSS nesting style to only declare the class once, so it's easier to change:

```css
/* Wrong: it's not easy to change the class name */
.button {
  --color: white;
  --bg-color: blue;

  color: var(--color);
  background: var(--bg-color);
}
.button:hover {
  color: var(--bg-color);
  background: var(--color);
}

/* Much better, the class is defined only once */
.button {
  --color: white;
  --bg-color: blue;

  color: var(--color);
  background: var(--bg-color);

  &:hover {
    color: var(--bg-color);
    background: var(--color);
  }
}
```

In the current format, this class is always `.host`. This allows us to replace it with something else easily.
In the vs code plugin, when a module is imported, the `.host` class is replaced with a class following the `.<package>_<module>` pattern ([see video](https://github.com/CSS-Galore/vscode-css-galore)), and the class is automatically selected to easily edit it.
This method would allow us to, for example, import a module from a CDN with a custom class name. Example:

```css
@import "https://cdn.css.gal/<package>/<module>.css?class=my-class-name";
```

This is an open discussion, feedback is very welcome!

**Comment by rdela** [comment]
> In this issue, we want to discuss the best way to store and organize CSS packages for better reusability.

I like this as the initial goal.
 
> - Every package has a README.md file with the description of the package, how to use it, the author, etc.

I am not certain we need readmes, other than: 

1. git hosts want one for repos
2. the registry could reuse it.

>   - Is this file enough? Do we need a more structured format (like JSON, toml, etc) to store info like author, license, etc?

Always bugs me that the license file has to be included separately after specifying it in package.json (or specified after adding the license file, however one looks at it), maybe we can avoid that duplication and repetition by using a standardized comment at the top of the CSS or HTML file for all metadata? Seems like you are already leaning this way and there is precedent like style.css in WP themes or JSDoc.
 
> > Some package registries have the concept of "scope" to group different packages under the same scope (scopes used to be the author name or a framework with several packages) making the paths a bit bigger `<scope>/<package>/<module>`. Do we need it?
> > The problem I see is not all packages need a scope. It's pretty common to see scopes and packages with the same name. An alternative solution could be to allow submodules if needed. For example: `<package>/<module>/<submodule>`. This would fit well for simple packages (with just one module) and big packages with many modules and submodules.

On one hand leaving out scope makes things easier all around, and submodules fit better with the cascade design of CSS itself, and history of CSS modules.

On the other hand everyone ends up adding scopes later on anyway, so by leaving it out are we doomed to add it more awkwardly in the future?

> The current modules are stored in HTML files. HTML is a very versatile format that can contain stuff of different types. The HTML follows the following structure:
> 
> ```html
> 
> 
> 
> <p>HTML elements for the demo</p>
> 
> <style>
> 
>   .host {
> 
>     /* User settings */
> 
>     ...
> 
>     /* Implementation */
> 
>     ...
> 
>   }
> 
> </style>
> 
> <style>
> 
>   /* Additional styles only for the demo */
> 
> </style>
> 
> ```
> 
> - We use an HTML comment to include a description of the module in markdown format.
> 
>   - Is this enough? Should we have a more structured format like JSON or YAML?
> 
> - The first `<style>` element is considered the code of the module. It's the code that you will get when importing the module into your project.
> 
> - Additional `<style>` elements are considered styles for the demo but don't belong to the module. They are ignored when importing the module into a project.
> 
> This format allows us to store not only the CSS code of the module but also everything needed to test the code in a browser in just a single file. It works out of the box, without any tooling, just open this file in a browser and you will see a demo of the module.

This is clever in many ways but I think slightly too clever for its own good. My most immediate suggestion is to make the first style tag an `import` instead, so that the CSS code we care about is self-contained in a CSS file I can import, or throw on a CDN, or open in an editor, select all, copy, and paste whenever I want without having to fussily select the contents of the first style tag.
 
> - What happens if in our code we are using the same CSS properties for another purpose? Should we encourage the use of underscored property names?

Underscores are interesting, as would be an enforced namespace like the `.host` class, maybe `host_`? Then it’s easier to swap with find and replace?

> In the current format, this class is always `.host`. This allows us to replace it with something else easily.
> 
> In the vs code plugin, when a module is imported, the `.host` class is replaced with a class following the `.<package>_<module>` pattern ([see video](https://github.com/CSS-Galore/vscode-css-galore)), and the class is automatically selected to easily edit it.
> 
> This method would allow us to, for example, import a module from a CDN with a custom class name. Example:
> 
> ```css
> 
> @import "https://cdn.css.gal/<package>/<module>.css?class=my-class-name";
> 
> ```

This sounds great so we nest everything under host? [Nesting selector](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting#child_selectors) only when necessary or encouraged always?

```css
.host {
  --host_border: 1px solid black;
  --host_border-radius: 0.5rem;
  --host_family: Baskerville;
  --host_style: italic;

  border: var(--host_border);
  border-radius: var(--host_border-radius);

  & figcaption {
    font-family: var(--host_family);
    font-style: var(--host_style);
  }
}
```
